volumes:
  postgresql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./postgresql/data
services:
  postgresql:
    image: postgres-image
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgresql7
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/db-files/
    ports:
      - 5432:5432
  tasks_service:
    image: tasks-service:crud
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DSN: postgresql://postgres:postgresql7@postgresql:5432/postgres
  comment_service:
    image: comment-service:comm
    ports:
      - "4000:4000"
    environment:
      POSTGRES_DSN: postgresql://postgres:postgresql7@postgresql:5432/postgres
